security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
       App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STAFF]
        ROLE_STAFF: []

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

        main:
            lazy: true
            provider: app_user_provider


            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\GoogleAuthenticator

            entry_point: App\Security\LoginFormAuthenticator

            logout:
                path: /logout
                target: /login

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 2592000
                path: /
                remember_me_parameter: _remember_me
                always_remember_me: false
                user_providers: [app_user_provider]

    access_control:
        - { path: ^/verify/email, roles: PUBLIC_ACCESS }
        - { path: ^/api/verify/email, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/hello$, roles: PUBLIC_ACCESS }
        - { path: ^/api/products, roles: PUBLIC_ACCESS }
        - { path: ^/api/staff, roles: ROLE_STAFF }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        # ADMIN ONLY ROUTES
        - { path: ^/admin/users, roles: ROLE_ADMIN }
        - { path: ^/admin/logs, roles: ROLE_ADMIN }
        - { path: ^/admin/reports, roles: ROLE_ADMIN }

        # STAFF + ADMIN
        - { path: ^/admin/dashboard, roles: ROLE_ADMIN }
        - { path: ^/admin/product, roles: ROLE_STAFF }
        - { path: ^/admin/orders, roles: ROLE_STAFF }

        # STAFF AREA
        - { path: ^/staff, roles: ROLE_STAFF }

        # PUBLIC ROUTES
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/cart, roles: PUBLIC_ACCESS }
        - { path: ^/menu, roles: PUBLIC_ACCESS }
        - { path: ^/my-orders, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

